"#version 300 es														\n"
"precision lowp float;													\n"
"																		\n"
"uniform	sampler2D	video;											\n"
"in			vec2		coord;											\n"
"out		vec4		outColor;										\n"
"																		\n"
"void main () {															\n"
"    outColor = texture (video, coord);									\n"
"}																		\n";
