"#version 300 es															\n"
"precision %s float;														\n"
"																			\n"
"uniform	usampler2D	Y;													\n"
"uniform	usampler2D	Cb;													\n"
"uniform	usampler2D	Cr;													\n"
"in			vec2		coord;												\n"
"out		vec4		outColor;											\n"
"																			\n"
"void main () {																\n"
"    outColor = vec4 (														\n"
"		float (texture (Y, coord).r) / 65535.0,								\n"
"		float (texture (Cb, coord).r) / 65535.0,							\n"
"		float (texture (Cr, coord).r) / 65535.0,							\n"
"		1.0);																\n"
"}																			\n";
