"#version 300 es														\n"
"precision %s float;													\n"
"																		\n"
"uniform	sampler2D	Y;												\n"
"uniform	sampler2D	Cb;												\n"
"uniform	sampler2D	Cr;												\n"
"in			vec2		coord;											\n"
"out		vec4		outColor;										\n"
"																		\n"
"void main () {															\n"
"    outColor = vec4 (texture (Y, coord).r,	texture (Cb, coord).r,		\n"
"		texture (Cr, coord).r, 1.0);									\n"
"}																		\n";
