"#version 300 es														\n"
"precision %s float;													\n"
"%s																		\n"
"																		\n"
"uniform	sampler2D	Y;												\n"
"uniform	sampler2D	Cb;												\n"
"uniform	sampler2D	Cr;												\n"
"#ifdef HWCHROMA														\n"
"uniform	float		pitch;											\n"
"#endif																	\n"
"in			vec2		coord;											\n"
"out		vec4		outColor;										\n"
"																		\n"
"void main () {															\n"
"#ifdef HWCHROMA														\n"
"	vec2 newCoord = coord + vec2 (pitch, 0.0);							\n"
"	outColor = vec4 (texture (Y, coord).r, texture (Cb, newCoord).r,	\n"
"		texture (Cr, newCoord).r, 1.0);									\n"
"#else																	\n"
"	outColor = vec4 (texture (Y, coord).r, texture (Cb, coord).r,		\n"
"		texture (Cr, coord).r, 1.0);									\n"
"#endif																	\n"
"}																		\n";
