"precision %s float;													\n"
"																		\n"
"uniform sampler2D texture;												\n"
"varying vec2      coord;												\n"
"																		\n"
"const float pitch = 1.0 / %i.0;										\n"
"																		\n"
"void main () {															\n"
"	float y = texture2D (texture, coord).r;								\n"
"	vec2 uv = mix (texture2D (texture, coord + vec2 (0.0, -pitch)).gb,	\n"
"		texture2D (texture, coord + vec2 (0.0, pitch)).gb,				\n"
"		fract (coord.y * pitch * 0.5));									\n"
"	gl_FragColor = vec3 (y,	uv);										\n"
"}																		\n";
