"precision %s float;													\n"
"																		\n"
"uniform sampler2D texture;												\n"
"varying vec2      coord;												\n"
"																		\n"
"const float pitch = 0.5 / %i.0;										\n"
"																		\n"
"void main () {															\n"
"	float y = texture2D (texture, coord).r;								\n"
"	vec2 uv = mix (texture2D (texture, coord + vec2 (-pitch, 0.0)).gb,	\n"
"		texture2D (texture, coord + vec2 (pitch, 0.0)).gb,				\n"
"		0.5);															\n"
"	gl_FragColor = vec4 (y,	uv, 1.0);									\n"
"}																		\n";
