"#version 300 es														\n"
"precision %s float;													\n"
"																		\n"
"uniform	sampler2D	video;											\n"
"uniform	float		pitch;											\n"
"in			vec2		coord;											\n"
"out		vec4		outColor;										\n"
"																		\n"
"void main () {															\n"
"	float y = texture (video, coord).r;									\n"
"	vec2 uv = mix (														\n"
"		texture (video, coord                    ).gb,					\n"
"		texture (video, coord + vec2 (pitch, 0.0)).gb,					\n"
"		0.5);															\n"
"	outColor = vec4 (y,	uv, 1.0);										\n"
"}																		\n";
